### PR TITLE
GitHub PR Commenting

### PR DESCRIPTION
**Pull request by louisefindlay23**
Currently a test (draft PR) to test using the bot to post a comment on a PR

### CODE REVIEW

**Comment by louisefindlay23** [comment]
A test command posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test command posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test command posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test command posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Review by Inoxia25 — APPROVED** [review]
Finally we got it working wohoo :rocket: 
Approvedd!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Pull request merged**
