### PR TITLE
Comment posting works again

### PR DESCRIPTION
**Pull request by louisefindlay23**
GitHub auth/commenting is now working by moving everything into the bot function and via the merging of two feature branches.

Posting a comment is now the `-github-comment-issue` command.

### CODE REVIEW

**Comment by louisefindlay23** [comment]
Now everything is working as it should. The issues was main.js was hardcoded to github-post so now changed it to contains github so future git bot commands work.

**Comment by louisefindlay23** [comment]
Will work on getting user input for issue number in new branch `issue-input`.

**Comment by louisefindlay23** [comment]
Wow,

**Comment by louisefindlay23** [comment]
User issue number input has been implemented in #10.

**Review by Inoxia25 — APPROVED** [review]
Seems like you refactored the code too! Looks great! 
Also,  we still have to implement github-comment-pr right?

**Comment by louisefindlay23** [comment]
Thanks, @Inoxia25. Kind of. GitHub commenting function works for issues and PRs. It depends whether we want to combine them or not. 

In my `bot-replies` branch, I'm moving the post comment code to a function so (when this hopefully work), we could probably do separate commands and just called the `postComment()` function.

**Pull request merged**
