### PR TITLE
Fix Unrelated Histories and Initial Discord Bot Creation

### PR DESCRIPTION
**Pull request by louisefindlay23**
Fix unrelated histories issue from template unrelated main and staging branches due to discord-bot branch being created from main.

Also contains work for discord-bot branch. @dtemir's initial Discord bot creation and my own improvements - see commit history.

### CODE REVIEW

**Review by dtemir — APPROVED** [review]
Looks great!

**Comment by louisefindlay23** [comment]
Hi

**Comment by louisefindlay23** [comment]
Hi

**Comment by louisefindlay23** [comment]
Hi

**Comment by louisefindlay23** [comment]
Hi

**Comment by louisefindlay23** [comment]
Hi

**Comment by louisefindlay23** [comment]
Hi

**Comment by louisefindlay23** [comment]
Hi

**Comment by louisefindlay23** [comment]
Hi

**Comment by louisefindlay23** [comment]
Hi

**Comment by louisefindlay23** [comment]
Hi

**Comment by louisefindlay23** [comment]
Hi

**Pull request merged**
